// ─── Application-wide constants for the AI English Learning Platform ───────────

import type {
  Achievement,
  DailyGoal,
  NavItem,
  SubscriptionPlan,
  VocabularyWord,
} from '../types';

// ── CEFR Levels ────────────────────────────────────────────────────────────────

export interface LevelMeta {
  name: string;
  code: string;
  minXP: number;
  color: string;       // Tailwind text colour class
  bgColor: string;     // Tailwind bg+text badge class
  borderColor: string; // Tailwind border colour class
  emoji: string;
  description: string;
}

export const LEVELS: LevelMeta[] = [
  {
    name: 'Beginner',
    code: 'A1',
    minXP: 0,
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-100 text-emerald-800',
    borderColor: 'border-emerald-400',
    emoji: '🌱',
    description: 'Can understand and use familiar everyday expressions.',
  },
  {
    name: 'Elementary',
    code: 'A2',
    minXP: 1000,
    color: 'text-green-500',
    bgColor: 'bg-green-100 text-green-800',
    borderColor: 'border-green-400',
    emoji: '🌿',
    description: 'Can communicate in simple, routine tasks on familiar topics.',
  },
  {
    name: 'Intermediate',
    code: 'B1',
    minXP: 3000,
    color: 'text-blue-500',
    bgColor: 'bg-blue-100 text-blue-800',
    borderColor: 'border-blue-400',
    emoji: '💧',
    description: 'Can deal with most situations likely to arise while travelling.',
  },
  {
    name: 'Upper-Intermediate',
    code: 'B2',
    minXP: 7000,
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-100 text-indigo-800',
    borderColor: 'border-indigo-400',
    emoji: '🔷',
    description: 'Can interact with a degree of fluency with native speakers.',
  },
  {
    name: 'Advanced',
    code: 'C1',
    minXP: 14000,
    color: 'text-purple-500',
    bgColor: 'bg-purple-100 text-purple-800',
    borderColor: 'border-purple-400',
    emoji: '⚡',
    description: 'Can express ideas fluently and spontaneously without obvious searching.',
  },
  {
    name: 'Mastery',
    code: 'C2',
    minXP: 25000,
    color: 'text-amber-500',
    bgColor: 'bg-amber-100 text-amber-800',
    borderColor: 'border-amber-400',
    emoji: '👑',
    description: 'Can understand with ease virtually everything heard or read.',
  },
];

// ── XP thresholds (kept separate for quick lookup) ────────────────────────────

export const XP_THRESHOLDS: Record<string, number> = {
  A1: 0,
  A2: 1000,
  B1: 3000,
  B2: 7000,
  C1: 14000,
  C2: 25000,
};

// ── Subscription Plans ─────────────────────────────────────────────────────────

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'free',
    name: 'Free',
    price_monthly: 0,
    price_yearly: 0,
    ai_messages_per_day: 10,
    max_flashcards: 50,
    is_popular: false,
    features: [
      '10 AI messages per day',
      'Up to 50 flashcards',
      'Access to A1 & A2 lessons',
      'Basic grammar checker',
      'Daily streak tracking',
      'Community leaderboard',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price_monthly: 9.99,
    price_yearly: 83.99,   // ~30 % saving
    ai_messages_per_day: 100,
    max_flashcards: 500,
    is_popular: true,
    badge: 'Most Popular',
    features: [
      '100 AI messages per day',
      'Up to 500 flashcards',
      'Full access to all CEFR levels',
      'Advanced grammar analysis',
      'Speaking practice with AI feedback',
      'IELTS practice module',
      'Offline lesson downloads',
      'Priority support',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    price_monthly: 19.99,
    price_yearly: 167.99,   // ~30 % saving
    ai_messages_per_day: null,  // unlimited
    max_flashcards: null,       // unlimited
    is_popular: false,
    badge: 'Best Value',
    features: [
      'Unlimited AI messages',
      'Unlimited flashcards',
      'Everything in Pro',
      '1-on-1 live AI tutoring sessions',
      'Personalised learning path',
      'Business English module',
      'Interview preparation',
      'Certificate of completion',
      'Early access to new features',
      'Dedicated account manager',
    ],
  },
];

// ── Lesson Categories ──────────────────────────────────────────────────────────

export interface LessonCategory {
  id: string;
  label: string;
  icon: string;
  color: string;
  description: string;
}

export const LESSON_CATEGORIES: LessonCategory[] = [
  {
    id: 'grammar',
    label: 'Grammar',
    icon: 'BookOpen',
    color: 'text-blue-500',
    description: 'Master English grammar rules and structures.',
  },
  {
    id: 'vocabulary',
    label: 'Vocabulary',
    icon: 'Layers',
    color: 'text-green-500',
    description: 'Expand your word knowledge with spaced repetition.',
  },
  {
    id: 'speaking',
    label: 'Speaking',
    icon: 'Mic',
    color: 'text-red-500',
    description: 'Improve fluency with AI-powered speaking exercises.',
  },
  {
    id: 'listening',
    label: 'Listening',
    icon: 'Headphones',
    color: 'text-purple-500',
    description: 'Train your ear with real English audio content.',
  },
  {
    id: 'reading',
    label: 'Reading',
    icon: 'FileText',
    color: 'text-amber-500',
    description: 'Develop reading comprehension at your own pace.',
  },
  {
    id: 'writing',
    label: 'Writing',
    icon: 'PenLine',
    color: 'text-indigo-500',
    description: 'Write clearly and confidently with AI corrections.',
  },
];

// ── Achievements ───────────────────────────────────────────────────────────────

export const ACHIEVEMENTS: Achievement[] = [
  // ── Lesson milestones ──────────────────────────────────────────────────
  {
    id: 'first_lesson',
    title: 'First Step',
    description: 'Complete your very first lesson.',
    icon: '🎓',
    xp_reward: 50,
    condition: 'lessons_completed',
    threshold: 1,
    rarity: 'common',
  },
  {
    id: 'lessons_10',
    title: 'Eager Learner',
    description: 'Complete 10 lessons.',
    icon: '📚',
    xp_reward: 100,
    condition: 'lessons_completed',
    threshold: 10,
    rarity: 'common',
  },
  {
    id: 'lessons_50',
    title: 'Dedicated Student',
    description: 'Complete 50 lessons.',
    icon: '🏫',
    xp_reward: 300,
    condition: 'lessons_completed',
    threshold: 50,
    rarity: 'rare',
  },
  {
    id: 'lessons_100',
    title: 'Century Club',
    description: 'Complete 100 lessons.',
    icon: '💯',
    xp_reward: 750,
    condition: 'lessons_completed',
    threshold: 100,
    rarity: 'epic',
  },
  // ── Streak achievements ────────────────────────────────────────────────
  {
    id: 'streak_3',
    title: 'On Fire',
    description: 'Maintain a 3-day learning streak.',
    icon: '🔥',
    xp_reward: 30,
    condition: 'current_streak',
    threshold: 3,
    rarity: 'common',
  },
  {
    id: 'streak_7',
    title: '7-Day Warrior',
    description: 'Maintain a 7-day learning streak.',
    icon: '⚔️',
    xp_reward: 70,
    condition: 'current_streak',
    threshold: 7,
    rarity: 'common',
  },
  {
    id: 'streak_30',
    title: 'Monthly Champion',
    description: 'Maintain a 30-day learning streak.',
    icon: '🗓️',
    xp_reward: 500,
    condition: 'current_streak',
    threshold: 30,
    rarity: 'rare',
  },
  {
    id: 'streak_100',
    title: 'Unstoppable',
    description: 'Maintain a 100-day learning streak.',
    icon: '💥',
    xp_reward: 2000,
    condition: 'current_streak',
    threshold: 100,
    rarity: 'legendary',
  },
  // ── Vocabulary achievements ────────────────────────────────────────────
  {
    id: 'words_10',
    title: 'Word Collector',
    description: 'Learn your first 10 words.',
    icon: '📖',
    xp_reward: 50,
    condition: 'words_learned',
    threshold: 10,
    rarity: 'common',
  },
  {
    id: 'words_100',
    title: 'Vocabulary Builder',
    description: 'Learn 100 vocabulary words.',
    icon: '📝',
    xp_reward: 200,
    condition: 'words_learned',
    threshold: 100,
    rarity: 'rare',
  },
  {
    id: 'words_500',
    title: 'Word Master',
    description: 'Learn 500 vocabulary words.',
    icon: '🔑',
    xp_reward: 800,
    condition: 'words_learned',
    threshold: 500,
    rarity: 'epic',
  },
  {
    id: 'words_1000',
    title: 'Lexicon Legend',
    description: 'Learn 1,000 vocabulary words.',
    icon: '📜',
    xp_reward: 2500,
    condition: 'words_learned',
    threshold: 1000,
    rarity: 'legendary',
  },
  // ── XP / Level achievements ────────────────────────────────────────────
  {
    id: 'xp_1000',
    title: 'Rising Star',
    description: 'Earn 1,000 total XP.',
    icon: '⭐',
    xp_reward: 100,
    condition: 'total_xp',
    threshold: 1000,
    rarity: 'common',
  },
  {
    id: 'xp_5000',
    title: 'XP Hunter',
    description: 'Earn 5,000 total XP.',
    icon: '🌟',
    xp_reward: 300,
    condition: 'total_xp',
    threshold: 5000,
    rarity: 'rare',
  },
  {
    id: 'xp_25000',
    title: 'Grand Master',
    description: 'Reach Mastery level (25,000 XP).',
    icon: '👑',
    xp_reward: 1000,
    condition: 'total_xp',
    threshold: 25000,
    rarity: 'legendary',
  },
  // ── Speaking achievements ──────────────────────────────────────────────
  {
    id: 'first_speaking',
    title: 'First Words',
    description: 'Complete your first speaking session.',
    icon: '🎤',
    xp_reward: 75,
    condition: 'speaking_sessions',
    threshold: 1,
    rarity: 'common',
  },
  {
    id: 'speaking_10',
    title: 'Speaker',
    description: 'Complete 10 speaking sessions.',
    icon: '🗣️',
    xp_reward: 250,
    condition: 'speaking_sessions',
    threshold: 10,
    rarity: 'rare',
  },
  // ── Skill achievements ─────────────────────────────────────────────────
  {
    id: 'grammar_guru',
    title: 'Grammar Guru',
    description: 'Achieve a perfect score on 5 grammar quizzes.',
    icon: '✏️',
    xp_reward: 300,
    condition: 'perfect_grammar_quizzes',
    threshold: 5,
    rarity: 'rare',
  },
  {
    id: 'perfect_score',
    title: 'Perfectionist',
    description: 'Score 100% on any quiz.',
    icon: '💎',
    xp_reward: 150,
    condition: 'perfect_quiz_score',
    threshold: 1,
    rarity: 'common',
  },
  {
    id: 'ielts_ready',
    title: 'IELTS Ready',
    description: 'Complete all IELTS practice sections.',
    icon: '📋',
    xp_reward: 500,
    condition: 'ielts_sections_completed',
    threshold: 4,
    rarity: 'epic',
  },
  {
    id: 'night_owl',
    title: 'Night Owl',
    description: 'Complete a lesson after 10 PM.',
    icon: '🦉',
    xp_reward: 50,
    condition: 'night_lesson',
    threshold: 1,
    rarity: 'common',
  },
  {
    id: 'early_bird',
    title: 'Early Bird',
    description: 'Complete a lesson before 7 AM.',
    icon: '🐦',
    xp_reward: 50,
    condition: 'morning_lesson',
    threshold: 1,
    rarity: 'common',
  },
  {
    id: 'minutes_1000',
    title: 'Time Investor',
    description: 'Practice for 1,000 total minutes.',
    icon: '⏱️',
    xp_reward: 400,
    condition: 'minutes_practiced',
    threshold: 1000,
    rarity: 'rare',
  },
];

// ── Navigation Items ───────────────────────────────────────────────────────────

export const NAV_ITEMS: NavItem[] = [
  {
    label: 'Dashboard',
    href: '/app',
    icon: 'LayoutDashboard',
  },
  {
    label: 'Lessons',
    href: '/app/lessons',
    icon: 'BookOpen',
  },
  {
    label: 'Vocabulary',
    href: '/app/vocabulary',
    icon: 'Layers',
  },
  {
    label: 'Flashcards',
    href: '/app/flashcards',
    icon: 'CreditCard',
  },
  {
    label: 'AI Tutor',
    href: '/app/chat',
    icon: 'Bot',
  },
  {
    label: 'Speaking',
    href: '/app/speaking',
    icon: 'Mic',
    requiresPro: true,
  },
  {
    label: 'IELTS Prep',
    href: '/app/ielts',
    icon: 'ClipboardList',
    requiresPro: true,
  },
  {
    label: 'Leaderboard',
    href: '/app/leaderboard',
    icon: 'Trophy',
  },
  {
    label: 'Achievements',
    href: '/app/achievements',
    icon: 'Medal',
  },
  {
    label: 'Settings',
    href: '/app/settings',
    icon: 'Settings',
  },
];

// ── Sample Vocabulary (20 words with Uzbek translations) ──────────────────────

export const SAMPLE_VOCABULARY: VocabularyWord[] = [
  {
    id: 'v1',
    word: 'Accomplish',
    definition: 'To successfully achieve or complete something.',
    example_sentence: 'She accomplished all her goals for the year.',
    translation_uz: 'Erishmoq, bajarmoq',
    pronunciation: '/əˈkɒmplɪʃ/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'medium',
    level: 'B1',
    synonyms: ['achieve', 'complete', 'fulfil'],
    antonyms: ['fail', 'abandon'],
  },
  {
    id: 'v2',
    word: 'Abundant',
    definition: 'Existing or available in large quantities; more than enough.',
    example_sentence: 'The region has abundant natural resources.',
    translation_uz: 'Mo\'l, ko\'p',
    pronunciation: '/əˈbʌndənt/',
    audio_url: null,
    category: 'adjectives',
    difficulty: 'medium',
    level: 'B1',
    synonyms: ['plentiful', 'ample', 'rich'],
    antonyms: ['scarce', 'rare', 'insufficient'],
  },
  {
    id: 'v3',
    word: 'Ambiguous',
    definition: 'Open to more than one interpretation; not having one obvious meaning.',
    example_sentence: 'The wording of the contract was ambiguous.',
    translation_uz: 'Noaniq, ikki ma\'noli',
    pronunciation: '/æmˈbɪɡjuəs/',
    audio_url: null,
    category: 'adjectives',
    difficulty: 'hard',
    level: 'C1',
    synonyms: ['unclear', 'vague', 'equivocal'],
    antonyms: ['clear', 'unambiguous', 'definite'],
  },
  {
    id: 'v4',
    word: 'Benefit',
    definition: 'An advantage or profit gained from something.',
    example_sentence: 'Regular exercise has many health benefits.',
    translation_uz: 'Foyda, manfaat',
    pronunciation: '/ˈbenɪfɪt/',
    audio_url: null,
    category: 'nouns',
    difficulty: 'easy',
    level: 'A2',
    synonyms: ['advantage', 'gain', 'profit'],
    antonyms: ['disadvantage', 'harm', 'loss'],
  },
  {
    id: 'v5',
    word: 'Collaborate',
    definition: 'To work jointly with others, especially on a project.',
    example_sentence: 'The two companies collaborated on the new product launch.',
    translation_uz: 'Hamkorlik qilmoq',
    pronunciation: '/kəˈlæbəreɪt/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'medium',
    level: 'B2',
    synonyms: ['cooperate', 'work together', 'partner'],
    antonyms: ['compete', 'oppose'],
  },
  {
    id: 'v6',
    word: 'Comprehensive',
    definition: 'Complete and including everything that is necessary.',
    example_sentence: 'The report provides a comprehensive overview of the situation.',
    translation_uz: 'Keng qamrovli, to\'liq',
    pronunciation: '/ˌkɒmprɪˈhensɪv/',
    audio_url: null,
    category: 'adjectives',
    difficulty: 'hard',
    level: 'C1',
    synonyms: ['thorough', 'complete', 'exhaustive'],
    antonyms: ['incomplete', 'partial', 'limited'],
  },
  {
    id: 'v7',
    word: 'Determine',
    definition: 'To cause something to occur in a particular way; to find out.',
    example_sentence: 'The investigation will determine the cause of the accident.',
    translation_uz: 'Aniqlash, belgilash',
    pronunciation: '/dɪˈtɜːmɪn/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'medium',
    level: 'B1',
    synonyms: ['establish', 'decide', 'ascertain'],
    antonyms: ['ignore', 'overlook'],
  },
  {
    id: 'v8',
    word: 'Efficient',
    definition: 'Achieving maximum productivity with minimum wasted effort.',
    example_sentence: 'We need a more efficient way to process these requests.',
    translation_uz: 'Samarali, unumli',
    pronunciation: '/ɪˈfɪʃənt/',
    audio_url: null,
    category: 'adjectives',
    difficulty: 'medium',
    level: 'B1',
    synonyms: ['productive', 'effective', 'competent'],
    antonyms: ['inefficient', 'wasteful', 'slow'],
  },
  {
    id: 'v9',
    word: 'Emerge',
    definition: 'To come into view or become known.',
    example_sentence: 'New evidence has emerged that could change the verdict.',
    translation_uz: 'Paydo bo\'lmoq, namoyon bo\'lmoq',
    pronunciation: '/ɪˈmɜːdʒ/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'medium',
    level: 'B2',
    synonyms: ['appear', 'surface', 'arise'],
    antonyms: ['disappear', 'vanish', 'submerge'],
  },
  {
    id: 'v10',
    word: 'Fundamental',
    definition: 'Forming a necessary base or core; of central importance.',
    example_sentence: 'Trust is fundamental to any successful relationship.',
    translation_uz: 'Asosiy, muhim',
    pronunciation: '/ˌfʌndəˈmentəl/',
    audio_url: null,
    category: 'adjectives',
    difficulty: 'hard',
    level: 'C1',
    synonyms: ['basic', 'essential', 'primary'],
    antonyms: ['secondary', 'minor', 'insignificant'],
  },
  {
    id: 'v11',
    word: 'Generate',
    definition: 'To produce or create something.',
    example_sentence: 'The project will generate hundreds of new jobs.',
    translation_uz: 'Hosil qilmoq, yaratmoq',
    pronunciation: '/ˈdʒenəreɪt/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'easy',
    level: 'B1',
    synonyms: ['create', 'produce', 'yield'],
    antonyms: ['destroy', 'eliminate', 'reduce'],
  },
  {
    id: 'v12',
    word: 'Hesitate',
    definition: 'To pause before saying or doing something, often due to uncertainty.',
    example_sentence: 'Don\'t hesitate to ask if you need any help.',
    translation_uz: 'Ikkilanmoq, cho\'zilib qolmoq',
    pronunciation: '/ˈhezɪteɪt/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'medium',
    level: 'B1',
    synonyms: ['pause', 'waver', 'delay'],
    antonyms: ['proceed', 'decide', 'act'],
  },
  {
    id: 'v13',
    word: 'Implement',
    definition: 'To put a plan or decision into effect.',
    example_sentence: 'The government will implement the new policy next year.',
    translation_uz: 'Amalga oshirmoq, joriy etmoq',
    pronunciation: '/ˈɪmplɪment/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'medium',
    level: 'B2',
    synonyms: ['execute', 'apply', 'enforce'],
    antonyms: ['abandon', 'cancel', 'withdraw'],
  },
  {
    id: 'v14',
    word: 'Inevitable',
    definition: 'Certain to happen; unavoidable.',
    example_sentence: 'Change is inevitable in any growing organisation.',
    translation_uz: 'Muqarrar, oldini olish mumkin bo\'lmagan',
    pronunciation: '/ɪnˈevɪtəbəl/',
    audio_url: null,
    category: 'adjectives',
    difficulty: 'hard',
    level: 'C1',
    synonyms: ['unavoidable', 'certain', 'inescapable'],
    antonyms: ['avoidable', 'uncertain', 'preventable'],
  },
  {
    id: 'v15',
    word: 'Justify',
    definition: 'To show or prove that something is right or reasonable.',
    example_sentence: 'Can you justify the extra cost?',
    translation_uz: 'Asoslash, oqlash',
    pronunciation: '/ˈdʒʌstɪfaɪ/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'medium',
    level: 'B2',
    synonyms: ['explain', 'defend', 'validate'],
    antonyms: ['condemn', 'oppose', 'refute'],
  },
  {
    id: 'v16',
    word: 'Negotiate',
    definition: 'To try to reach an agreement through discussion.',
    example_sentence: 'They negotiated a better salary package.',
    translation_uz: 'Muzokaralar olib bormoq, kelishmoq',
    pronunciation: '/nɪˈɡoʊʃieɪt/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'medium',
    level: 'B2',
    synonyms: ['discuss', 'bargain', 'mediate'],
    antonyms: ['refuse', 'demand', 'dictate'],
  },
  {
    id: 'v17',
    word: 'Persist',
    definition: 'To continue firmly in a course of action despite difficulty.',
    example_sentence: 'She persisted with her studies despite the challenges.',
    translation_uz: 'Qat\'iyat bilan davom ettirmoq, turib olmoq',
    pronunciation: '/pəˈsɪst/',
    audio_url: null,
    category: 'verbs',
    difficulty: 'medium',
    level: 'B2',
    synonyms: ['persevere', 'continue', 'endure'],
    antonyms: ['give up', 'quit', 'abandon'],
  },
  {
    id: 'v18',
    word: 'Significant',
    definition: 'Important or large enough to have an effect or to be noticed.',
    example_sentence: 'There has been a significant improvement in his performance.',
    translation_uz: 'Muhim, ahamiyatli',
    pronunciation: '/sɪɡˈnɪfɪkənt/',
    audio_url: null,
    category: 'adjectives',
    difficulty: 'easy',
    level: 'B1',
    synonyms: ['important', 'notable', 'considerable'],
    antonyms: ['insignificant', 'minor', 'trivial'],
  },
  {
    id: 'v19',
    word: 'Subsequently',
    definition: 'After a particular thing has happened; afterwards.',
    example_sentence: 'He was arrested and subsequently released on bail.',
    translation_uz: 'Keyinchalik, undan keyin',
    pronunciation: '/ˈsʌbsɪkwəntli/',
    audio_url: null,
    category: 'adverbs',
    difficulty: 'hard',
    level: 'C1',
    synonyms: ['afterwards', 'later', 'thereafter'],
    antonyms: ['previously', 'beforehand', 'earlier'],
  },
  {
    id: 'v20',
    word: 'Versatile',
    definition: 'Able to adapt or be adapted to many different functions or activities.',
    example_sentence: 'Python is a versatile programming language used in many fields.',
    translation_uz: 'Ko\'p qirrali, moslashuvchan',
    pronunciation: '/ˈvɜːsətaɪl/',
    audio_url: null,
    category: 'adjectives',
    difficulty: 'hard',
    level: 'C1',
    synonyms: ['adaptable', 'flexible', 'multi-purpose'],
    antonyms: ['inflexible', 'limited', 'single-purpose'],
  },
];

// ── Daily Goals ────────────────────────────────────────────────────────────────

export const DAILY_GOALS: DailyGoal[] = [
  { label: 'Casual',     minutes: 5,  xp_per_day: 20  },
  { label: 'Regular',    minutes: 10, xp_per_day: 50  },
  { label: 'Serious',    minutes: 20, xp_per_day: 100 },
  { label: 'Intensive',  minutes: 30, xp_per_day: 150 },
  { label: 'Dedicated',  minutes: 60, xp_per_day: 300 },
];

// ── App metadata ───────────────────────────────────────────────────────────────

export const APP_NAME = 'EnglishAI';
export const APP_DESCRIPTION = 'AI-powered English learning for Uzbek speakers';
export const SUPPORT_EMAIL = 'support@englishai.uz';

// ── Pagination ─────────────────────────────────────────────────────────────────

export const DEFAULT_PAGE_SIZE = 20;
export const LEADERBOARD_SIZE = 50;

// ── SM-2 Spaced Repetition defaults ────────────────────────────────────────────

export const SM2_DEFAULTS = {
  ease_factor: 2.5,
  interval: 1,       // days
  repetitions: 0,
} as const;
